-- public.class_room definition

-- Drop table

-- DROP TABLE public.class_room;

CREATE TABLE public.class_room (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	code varchar(255) NULL,
	current_semester int4 NULL,
	description varchar(255) NULL,
	end_time date NULL,
	"name" varchar(255) NULL,
	start_time date NULL,
	CONSTRAINT class_room_pkey PRIMARY KEY (id),
	CONSTRAINT uk1p0ms7rg2qbccx9eel7tjonfd UNIQUE (code)
);

CREATE TABLE public.student (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	adress varchar(255) NULL,
	date_of_birth date NULL,
	gender int4 NULL,
	"name" varchar(255) NULL,
	student_id varchar(255) NULL,
	tel varchar(255) NULL,
	class_id int8 NULL,
	CONSTRAINT student_pkey PRIMARY KEY (id),
	CONSTRAINT fkt3mj3ri10grhbs2k0vn1ek1yn FOREIGN KEY (class_id) REFERENCES public.class_room(id)
);